/**
 * Generate a comprehensive analysis report in Markdown format
 */

export function generateMarkdownReport(nodes, edges, analysisData = {}) {
    const timestamp = new Date().toISOString();
    const date = new Date().toLocaleDateString();
    
    // Calculate statistics
    const stats = calculateStatistics(nodes, edges);
    const riskBreakdown = calculateRiskBreakdown(nodes);
    const typeBreakdown = calculateTypeBreakdown(nodes);
    
    let report = `# Code Analysis Report
Generated: ${date}

---

## 1. Executive Summary

This report provides a comprehensive analysis of the codebase structure, dependencies, and risk assessment.

- **Total Nodes**: ${stats.totalNodes}
- **Total Edges**: ${stats.totalEdges}
- **Files Analyzed**: ${stats.totalFiles}
- **High Risk Nodes**: ${riskBreakdown.high + riskBreakdown.critical}
- **Average Complexity**: ${stats.avgComplexity.toFixed(2)}

---

## 2. Architecture Overview

### Node Distribution by Type

${Object.entries(typeBreakdown).map(([type, count]) => 
    `- **${type}**: ${count} nodes`
).join('\n')}

### Risk Level Distribution

${Object.entries(riskBreakdown).map(([level, count]) => 
    `- **${level.toUpperCase()}**: ${count} nodes`
).join('\n')}

---

## 3. Node Classification

### Breakdown by Classification

${generateNodeClassificationTable(nodes)}

---

## 4. Dependency Analysis

### Dependency Statistics

- **Total Dependencies**: ${stats.totalEdges}
- **Average Dependencies per Node**: ${stats.avgDependencies.toFixed(2)}
- **Most Connected Nodes**: ${stats.mostConnected}

### Dependency Graph Metrics

${generateDependencyMetrics(nodes, edges)}

---

## 5. Risk Analysis

### Critical Risk Nodes

${generateRiskNodesList(nodes, 'critical')}

### High Risk Nodes

${generateRiskNodesList(nodes, 'high')}

### Risk Factors Summary

${generateRiskFactorsSummary(nodes)}

---

## 6. Critical Paths

${generateCriticalPaths(nodes, edges)}

---

## 7. Sensitive Behaviors

${generateSensitiveBehaviors(nodes)}

---

## 8. Impact Analysis

${generateImpactAnalysis(nodes)}

---

## 9. Attack Paths

${generateAttackPaths(nodes, edges)}

---

## 10. Refactoring Suggestions

${generateRefactoringSuggestions(nodes)}

---

## 11. Dependency Risk

${generateDependencyRisk(nodes, edges)}

---

## 12. Graph Metrics

${generateGraphMetrics(nodes, edges)}

---

## 13. File Analysis

${generateFileAnalysis(nodes)}

---

## 14. Security Score

${generateSecurityScore(nodes)}

---

## 15. Recommendations

${generateRecommendations(nodes, riskBreakdown)}

---

*Report generated by CodeForge Analysis Tool*
*Timestamp: ${timestamp}*
`;

    return report;
}

function calculateStatistics(nodes, edges) {
    const files = new Set(nodes.map(n => n.file).filter(Boolean));
    const totalLoc = nodes.reduce((sum, n) => sum + (n.loc || 0), 0);
    const avgComplexity = totalLoc / nodes.length || 0;
    
    const dependencyCounts = {};
    edges.forEach(e => {
        dependencyCounts[e.source] = (dependencyCounts[e.source] || 0) + 1;
    });
    
    const mostConnected = Object.entries(dependencyCounts)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 3)
        .map(([id, count]) => {
            const node = nodes.find(n => n.id === id);
            return `${node?.name || id} (${count})`;
        })
        .join(', ') || 'None';
    
    return {
        totalNodes: nodes.length,
        totalEdges: edges.length,
        totalFiles: files.size,
        avgComplexity,
        avgDependencies: edges.length / nodes.length || 0,
        mostConnected
    };
}

function calculateRiskBreakdown(nodes) {
    const breakdown = { critical: 0, high: 0, moderate: 0, medium: 0, low: 0, none: 0 };
    nodes.forEach(node => {
        const risk = node.risk_level || node.risk || 'none';
        breakdown[risk] = (breakdown[risk] || 0) + 1;
    });
    return breakdown;
}

function calculateTypeBreakdown(nodes) {
    const breakdown = {};
    nodes.forEach(node => {
        const type = node.type || node.classification || 'unknown';
        breakdown[type] = (breakdown[type] || 0) + 1;
    });
    return breakdown;
}

function generateNodeClassificationTable(nodes) {
    const classifications = {};
    nodes.forEach(node => {
        const cls = node.classification || node.type || 'unknown';
        if (!classifications[cls]) classifications[cls] = [];
        classifications[cls].push(node);
    });
    
    let table = '| Classification | Count | Examples |\n|---|---|---|\n';
    Object.entries(classifications).forEach(([cls, nodeList]) => {
        const examples = nodeList.slice(0, 3).map(n => n.name).join(', ');
        table += `| ${cls} | ${nodeList.length} | ${examples} |\n`;
    });
    
    return table;
}

function generateDependencyMetrics(nodes, edges) {
    const inDegree = {};
    const outDegree = {};
    
    edges.forEach(e => {
        outDegree[e.source] = (outDegree[e.source] || 0) + 1;
        inDegree[e.target] = (inDegree[e.target] || 0) + 1;
    });
    
    const maxIn = Math.max(...Object.values(inDegree), 0);
    const maxOut = Math.max(...Object.values(outDegree), 0);
    
    return `- **Max In-Degree**: ${maxIn}
- **Max Out-Degree**: ${maxOut}
- **Average In-Degree**: ${(Object.values(inDegree).reduce((a, b) => a + b, 0) / nodes.length || 0).toFixed(2)}
- **Average Out-Degree**: ${(Object.values(outDegree).reduce((a, b) => a + b, 0) / nodes.length || 0).toFixed(2)}`;
}

function generateRiskNodesList(nodes, riskLevel) {
    const riskNodes = nodes.filter(n => (n.risk_level || n.risk) === riskLevel);
    
    if (riskNodes.length === 0) {
        return `No ${riskLevel} risk nodes detected.\n`;
    }
    
    let list = `Found ${riskNodes.length} ${riskLevel} risk node(s):\n\n`;
    riskNodes.slice(0, 10).forEach(node => {
        list += `### ${node.name}\n`;
        list += `- **File**: ${node.file || 'Unknown'}\n`;
        list += `- **Type**: ${node.type || node.classification || 'Unknown'}\n`;
        if (node.node_summary) {
            list += `- **Summary**: ${node.node_summary}\n`;
        }
        if (node.risk_analysis?.risk_factors) {
            list += `- **Risk Factors**:\n`;
            Object.entries(node.risk_analysis.risk_factors).forEach(([factor, data]) => {
                if (data.level && data.level !== 'none') {
                    list += `  - ${factor}: ${data.level} - ${data.reason}\n`;
                }
            });
        }
        list += '\n';
    });
    
    if (riskNodes.length > 10) {
        list += `\n*... and ${riskNodes.length - 10} more*\n`;
    }
    
    return list;
}

function generateRiskFactorsSummary(nodes) {
    const factorCounts = {};
    
    nodes.forEach(node => {
        if (node.risk_analysis?.risk_factors) {
            Object.entries(node.risk_analysis.risk_factors).forEach(([factor, data]) => {
                if (data.level && data.level !== 'none') {
                    if (!factorCounts[factor]) factorCounts[factor] = {};
                    factorCounts[factor][data.level] = (factorCounts[factor][data.level] || 0) + 1;
                }
            });
        }
    });
    
    if (Object.keys(factorCounts).length === 0) {
        return 'No specific risk factors detected.\n';
    }
    
    let summary = '| Risk Factor | Critical | High | Moderate | Low |\n|---|---|---|---|---|\n';
    Object.entries(factorCounts).forEach(([factor, levels]) => {
        summary += `| ${factor.replace(/_/g, ' ')} | ${levels.critical || 0} | ${levels.high || 0} | ${levels.moderate || 0} | ${levels.low || 0} |\n`;
    });
    
    return summary;
}

function generateCriticalPaths(nodes, edges) {
    const highRiskNodes = nodes.filter(n => ['critical', 'high'].includes(n.risk_level || n.risk));
    
    if (highRiskNodes.length === 0) {
        return 'No critical paths identified.\n';
    }
    
    let paths = `Identified ${highRiskNodes.length} high-risk nodes that may be part of critical paths:\n\n`;
    highRiskNodes.slice(0, 5).forEach(node => {
        paths += `- **${node.name}** (${node.file || 'Unknown'})\n`;
    });
    
    return paths;
}

function generateSensitiveBehaviors(nodes) {
    const sensitiveBehaviors = {};
    
    nodes.forEach(node => {
        if (node.sensitive_behaviors) {
            Object.entries(node.sensitive_behaviors).forEach(([behavior, value]) => {
                if (value) {
                    if (!sensitiveBehaviors[behavior]) sensitiveBehaviors[behavior] = [];
                    sensitiveBehaviors[behavior].push(node.name);
                }
            });
        }
    });
    
    if (Object.keys(sensitiveBehaviors).length === 0) {
        return 'No sensitive behaviors detected.\n';
    }
    
    let summary = '';
    Object.entries(sensitiveBehaviors).forEach(([behavior, nodeNames]) => {
        summary += `### ${behavior.replace(/_/g, ' ').toUpperCase()}\n`;
        summary += `Found in ${nodeNames.length} node(s): ${nodeNames.slice(0, 5).join(', ')}${nodeNames.length > 5 ? '...' : ''}\n\n`;
    });
    
    return summary;
}

function generateImpactAnalysis(nodes) {
    const nodesWithImpact = nodes.filter(n => n.impact_analysis);
    
    if (nodesWithImpact.length === 0) {
        return 'No impact analysis data available.\n';
    }
    
    const avgBlastRadius = nodesWithImpact.reduce((sum, n) => sum + (n.impact_analysis.blast_radius_score || 0), 0) / nodesWithImpact.length;
    const avgCriticalPath = nodesWithImpact.reduce((sum, n) => sum + (n.impact_analysis.critical_path_likelihood || 0), 0) / nodesWithImpact.length;
    
    let analysis = `### Impact Metrics\n\n`;
    analysis += `- **Average Blast Radius Score**: ${avgBlastRadius.toFixed(2)}/10\n`;
    analysis += `- **Average Critical Path Likelihood**: ${avgCriticalPath.toFixed(2)}/10\n\n`;
    
    const highImpact = nodesWithImpact
        .filter(n => n.impact_analysis.blast_radius_score >= 7 || n.impact_analysis.critical_path_likelihood >= 7)
        .slice(0, 5);
    
    if (highImpact.length > 0) {
        analysis += `### High Impact Nodes\n\n`;
        highImpact.forEach(node => {
            analysis += `- **${node.name}**: Blast Radius ${node.impact_analysis.blast_radius_score}/10, Critical Path ${node.impact_analysis.critical_path_likelihood}/10\n`;
        });
    }
    
    return analysis;
}

function generateAttackPaths(nodes, edges) {
    const externalNodes = nodes.filter(n => n.type === 'external' || n.classification === 'external');
    const criticalNodes = nodes.filter(n => (n.risk_level || n.risk) === 'critical');
    
    let paths = `### Potential Attack Surface\n\n`;
    paths += `- **External Entry Points**: ${externalNodes.length}\n`;
    paths += `- **Critical Nodes**: ${criticalNodes.length}\n\n`;
    
    if (externalNodes.length > 0) {
        paths += `### External Entry Points\n\n`;
        externalNodes.slice(0, 5).forEach(node => {
            paths += `- ${node.name} (${node.file || 'Unknown'})\n`;
        });
    }
    
    return paths;
}

function generateRefactoringSuggestions(nodes) {
    const highComplexity = nodes.filter(n => (n.loc || 0) > 100).sort((a, b) => (b.loc || 0) - (a.loc || 0));
    const highRisk = nodes.filter(n => ['critical', 'high'].includes(n.risk_level || n.risk));
    
    let suggestions = '';
    
    if (highComplexity.length > 0) {
        suggestions += `### High Complexity Nodes (Consider Refactoring)\n\n`;
        highComplexity.slice(0, 5).forEach(node => {
            suggestions += `- **${node.name}**: ${node.loc} LOC (${node.file || 'Unknown'})\n`;
        });
        suggestions += '\n';
    }
    
    if (highRisk.length > 0) {
        suggestions += `### High Risk Nodes (Require Review)\n\n`;
        highRisk.slice(0, 5).forEach(node => {
            suggestions += `- **${node.name}**: ${node.risk_level || node.risk} risk (${node.file || 'Unknown'})\n`;
        });
    }
    
    return suggestions || 'No immediate refactoring suggestions.\n';
}

function generateDependencyRisk(nodes, edges) {
    const externalDeps = edges.filter(e => {
        const target = nodes.find(n => n.id === e.target);
        return target && (target.type === 'external' || target.classification === 'external');
    });
    
    let risk = `### External Dependencies\n\n`;
    risk += `- **Total External Dependencies**: ${externalDeps.length}\n`;
    risk += `- **Dependency Risk Level**: ${externalDeps.length > 20 ? 'High' : externalDeps.length > 10 ? 'Moderate' : 'Low'}\n\n`;
    
    return risk;
}

function generateGraphMetrics(nodes, edges) {
    const density = (2 * edges.length) / (nodes.length * (nodes.length - 1)) || 0;
    
    return `- **Graph Density**: ${(density * 100).toFixed(2)}%
- **Total Nodes**: ${nodes.length}
- **Total Edges**: ${edges.length}
- **Average Degree**: ${((2 * edges.length) / nodes.length || 0).toFixed(2)}`;
}

function generateFileAnalysis(nodes) {
    const fileMap = {};
    
    nodes.forEach(node => {
        const file = node.file || 'Unknown';
        if (!fileMap[file]) {
            fileMap[file] = { nodes: [], totalLoc: 0, risks: { critical: 0, high: 0, moderate: 0, low: 0 } };
        }
        fileMap[file].nodes.push(node);
        fileMap[file].totalLoc += node.loc || 0;
        const risk = node.risk_level || node.risk || 'low';
        fileMap[file].risks[risk] = (fileMap[file].risks[risk] || 0) + 1;
    });
    
    const sortedFiles = Object.entries(fileMap)
        .sort((a, b) => b[1].totalLoc - a[1].totalLoc)
        .slice(0, 10);
    
    let analysis = '| File | Nodes | LOC | Critical | High | Moderate | Low |\n|---|---|---|---|---|---|---|\n';
    sortedFiles.forEach(([file, data]) => {
        const fileName = file.split('/').pop() || file;
        analysis += `| ${fileName} | ${data.nodes.length} | ${data.totalLoc} | ${data.risks.critical || 0} | ${data.risks.high || 0} | ${data.risks.moderate || 0} | ${data.risks.low || 0} |\n`;
    });
    
    return analysis;
}

function generateSecurityScore(nodes) {
    const totalNodes = nodes.length;
    const riskBreakdown = calculateRiskBreakdown(nodes);
    
    const score = 100 - (
        (riskBreakdown.critical * 20) +
        (riskBreakdown.high * 10) +
        (riskBreakdown.moderate * 5) +
        (riskBreakdown.medium * 5)
    ) / totalNodes;
    
    const normalizedScore = Math.max(0, Math.min(100, score));
    
    let rating = 'Excellent';
    if (normalizedScore < 40) rating = 'Poor';
    else if (normalizedScore < 60) rating = 'Fair';
    else if (normalizedScore < 80) rating = 'Good';
    
    return `### Overall Security Score: ${normalizedScore.toFixed(1)}/100 (${rating})

**Score Breakdown:**
- Critical Risk Nodes: ${riskBreakdown.critical} (-${riskBreakdown.critical * 20} points)
- High Risk Nodes: ${riskBreakdown.high} (-${riskBreakdown.high * 10} points)
- Moderate Risk Nodes: ${riskBreakdown.moderate} (-${riskBreakdown.moderate * 5} points)
- Low Risk Nodes: ${riskBreakdown.low}
`;
}

function generateRecommendations(nodes, riskBreakdown) {
    let recommendations = '';
    
    if (riskBreakdown.critical > 0) {
        recommendations += `1. **URGENT**: Address ${riskBreakdown.critical} critical risk node(s) immediately\n`;
    }
    
    if (riskBreakdown.high > 0) {
        recommendations += `2. **HIGH PRIORITY**: Review and mitigate ${riskBreakdown.high} high risk node(s)\n`;
    }
    
    if (riskBreakdown.moderate > 5) {
        recommendations += `3. **MODERATE PRIORITY**: Consider refactoring ${riskBreakdown.moderate} moderate risk nodes\n`;
    }
    
    const highComplexity = nodes.filter(n => (n.loc || 0) > 100).length;
    if (highComplexity > 0) {
        recommendations += `4. Refactor ${highComplexity} high-complexity functions to improve maintainability\n`;
    }
    
    recommendations += `5. Implement comprehensive testing for high-risk components\n`;
    recommendations += `6. Add security reviews for external-facing APIs\n`;
    recommendations += `7. Document critical paths and dependencies\n`;
    
    return recommendations || 'No specific recommendations at this time.\n';
}

export function downloadReport(nodes, edges, filename = 'code-analysis-report.md') {
    const report = generateMarkdownReport(nodes, edges);
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
